// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: oneknob_ui_ux

#ifndef _UI_COMP_ROLLER_STYLED_H
#define _UI_COMP_ROLLER_STYLED_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Roller_STYLED
#define UI_COMP_ROLLER_STYLED_ROLLER_STYLED 0
#define _UI_COMP_ROLLER_STYLED_NUM 1
lv_obj_t * ui_Roller_STYLED_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
