// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: oneknob_ui_ux

#ifndef _UI_COMP_CLOCKGROUP_H
#define _UI_COMP_CLOCKGROUP_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT clockgroup
#define UI_COMP_CLOCKGROUP_CLOCKGROUP 0
#define UI_COMP_CLOCKGROUP_SEC 1
#define UI_COMP_CLOCKGROUP_MIN 2
#define UI_COMP_CLOCKGROUP_HOUR 3
#define _UI_COMP_CLOCKGROUP_NUM 4
lv_obj_t * ui_clockgroup_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
