// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: oneknob_ui_ux

#include "../ui.h"

// COMPONENT Arc2

lv_obj_t * ui_Arc2_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Arc2;
    cui_Arc2 = lv_arc_create(comp_parent);
    lv_obj_set_width(cui_Arc2, 466);
    lv_obj_set_height(cui_Arc2, 466);
    lv_obj_set_align(cui_Arc2, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_Arc2, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(cui_Arc2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SNAPPABLE);      /// Flags
    lv_arc_set_value(cui_Arc2, 100);
    lv_arc_set_bg_angles(cui_Arc2, 0, 360);
    lv_obj_set_style_arc_width(cui_Arc2, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(cui_Arc2, 0, LV_PART_MAIN | LV_STATE_USER_2);

    lv_obj_set_style_arc_color(cui_Arc2, lv_color_hex(0x4040FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(cui_Arc2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(cui_Arc2, 30, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(cui_Arc2, 0, LV_PART_INDICATOR | LV_STATE_USER_2);

    lv_obj_set_style_opa(cui_Arc2, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_ARC2_NUM);
    children[UI_COMP_ARC2_ARC2] = cui_Arc2;
    lv_obj_add_event_cb(cui_Arc2, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Arc2, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_Arc2_create_hook(cui_Arc2);
    return cui_Arc2;
}

