// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: oneknob_ui_ux

#include "../ui.h"

// COMPONENT clockgroup

lv_obj_t * ui_clockgroup_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_clockgroup;
    cui_clockgroup = lv_obj_create(comp_parent);
    lv_obj_set_width(cui_clockgroup, 350);
    lv_obj_set_height(cui_clockgroup, 350);
    lv_obj_set_align(cui_clockgroup, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_clockgroup, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_clockgroup, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_clockgroup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_sec;
    cui_sec = lv_img_create(cui_clockgroup);
    lv_obj_set_width(cui_sec, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_sec, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_sec, 0);
    lv_obj_set_y(cui_sec, -67);
    lv_obj_set_align(cui_sec, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_sec, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(cui_sec, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_pivot(cui_sec, 15, 155);
    lv_img_set_angle(cui_sec, 12000);

    lv_obj_t * cui_min;
    cui_min = lv_img_create(cui_clockgroup);
    lv_obj_set_width(cui_min, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_min, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_min, 0);
    lv_obj_set_y(cui_min, -75);
    lv_obj_set_align(cui_min, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_min, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(cui_min, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_pivot(cui_min, 9, 153);

    lv_obj_t * cui_hour;
    cui_hour = lv_img_create(cui_clockgroup);
    lv_obj_set_width(cui_hour, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_hour, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_hour, 0);
    lv_obj_set_y(cui_hour, -45);
    lv_obj_set_align(cui_hour, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_hour, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(cui_hour, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_pivot(cui_hour, 9, 93);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_CLOCKGROUP_NUM);
    children[UI_COMP_CLOCKGROUP_CLOCKGROUP] = cui_clockgroup;
    children[UI_COMP_CLOCKGROUP_SEC] = cui_sec;
    children[UI_COMP_CLOCKGROUP_MIN] = cui_min;
    children[UI_COMP_CLOCKGROUP_HOUR] = cui_hour;
    lv_obj_add_event_cb(cui_clockgroup, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_clockgroup, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_clockgroup_create_hook(cui_clockgroup);
    return cui_clockgroup;
}

