// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: oneknob_ui_ux

#include "../ui.h"

// COMPONENT Roller_STYLED

lv_obj_t * ui_Roller_STYLED_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Roller_STYLED;
    cui_Roller_STYLED = lv_roller_create(comp_parent);
    lv_roller_set_options(cui_Roller_STYLED, "15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n29\n30",
                          LV_ROLLER_MODE_INFINITE);
    lv_obj_set_width(cui_Roller_STYLED, 100);
    lv_obj_set_height(cui_Roller_STYLED, 200);
    lv_obj_set_align(cui_Roller_STYLED, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(cui_Roller_STYLED, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(cui_Roller_STYLED, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(cui_Roller_STYLED, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(cui_Roller_STYLED, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(cui_Roller_STYLED, lv_color_hex(0xE64500), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Roller_STYLED, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_ROLLER_STYLED_NUM);
    children[UI_COMP_ROLLER_STYLED_ROLLER_STYLED] = cui_Roller_STYLED;
    lv_obj_add_event_cb(cui_Roller_STYLED, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Roller_STYLED, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_Roller_STYLED_create_hook(cui_Roller_STYLED);
    return cui_Roller_STYLED;
}

