// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: oneknob_ui_ux

#include "../ui.h"

void ui_Screen6_screen_init(void)
{
    ui_Screen6 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_GIFseq = lv_img_create(ui_Screen6);
    lv_img_set_src(ui_GIFseq, &ui_img_gif_frames_frame_00_png);
    lv_obj_set_width(ui_GIFseq, LV_SIZE_CONTENT);   /// 466
    lv_obj_set_height(ui_GIFseq, LV_SIZE_CONTENT);    /// 466
    lv_obj_set_x(ui_GIFseq, 4);
    lv_obj_set_y(ui_GIFseq, 0);
    lv_obj_set_align(ui_GIFseq, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_GIFseq, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_GIFseq, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Screen6, ui_event_Screen6, LV_EVENT_ALL, NULL);
    uic_GIFseq = ui_GIFseq;

}
