// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: oneknob_ui_ux

#include "../ui.h"

void ui_Screen5_screen_init(void)
{
    ui_Screen5 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_RollerSTYLED2 = lv_roller_create(ui_Screen5);
    lv_roller_set_options(ui_RollerSTYLED2, "Volume Control\nCustom Profile 1\nCustom Profile 2", LV_ROLLER_MODE_INFINITE);
    lv_obj_set_width(ui_RollerSTYLED2, 183);
    lv_obj_set_height(ui_RollerSTYLED2, 129);
    lv_obj_set_x(ui_RollerSTYLED2, 0);
    lv_obj_set_y(ui_RollerSTYLED2, 49);
    lv_obj_set_align(ui_RollerSTYLED2, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_RollerSTYLED2, &ui_font_Subtitle, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_RollerSTYLED2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_RollerSTYLED2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_RollerSTYLED2, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_RollerSTYLED2, lv_color_hex(0x2755AE), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RollerSTYLED2, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 0);
    lv_obj_set_y(ui_Label3, -89);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Profile Select");
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

}
