// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: HF-ESP-10-7-OLED

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_Image2;
void ui_event_background(lv_event_t * e);
lv_obj_t * ui_background;
lv_obj_t * ui_Image12;
lv_obj_t * ui_Arc1;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_background(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_image_set_property(ui_background, _UI_IMAGE_PROPERTY_IMAGE, & ui_img_2kaoji_png);
        _ui_image_set_property(ui_background, _UI_IMAGE_PROPERTY_IMAGE, & ui_img_3danta_png);
        _ui_image_set_property(ui_background, _UI_IMAGE_PROPERTY_IMAGE, & ui_img_4pisa_png);
        _ui_image_set_property(ui_background, _UI_IMAGE_PROPERTY_IMAGE, & ui_img_5liupai_png);
        _ui_image_set_property(ui_background, _UI_IMAGE_PROPERTY_IMAGE, & ui_img_6shutiao_png);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_image_set_property(ui_background, _UI_IMAGE_PROPERTY_IMAGE, & ui_img_2kaoji_png);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_image_set_property(ui_background, _UI_IMAGE_PROPERTY_IMAGE, & ui_img_3danta_png);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
