// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: HF-ESP-10-7-OLED

#ifndef _HF_ESP_10_7_OLED_UI_H
#define _HF_ESP_10_7_OLED_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Image2;
void ui_event_background(lv_event_t * e);
extern lv_obj_t * ui_background;
extern lv_obj_t * ui_Image12;
extern lv_obj_t * ui_Arc1;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_back480_png);    // assets/back480.png
LV_IMG_DECLARE(ui_img_1kaorou_png);    // assets/1kaorou.png
LV_IMG_DECLARE(ui_img_2kaoji_png);    // assets/2kaoji.png
LV_IMG_DECLARE(ui_img_3danta_png);    // assets/3danta.png
LV_IMG_DECLARE(ui_img_4pisa_png);    // assets/4pisa.png
LV_IMG_DECLARE(ui_img_5liupai_png);    // assets/5liupai.png
LV_IMG_DECLARE(ui_img_6shutiao_png);    // assets/6shutiao.png
LV_IMG_DECLARE(ui_img_back111_png);    // assets/back111.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
